#!/bin/bash

cd "$(dirname "$0")"

raw_day="$(echo "$1" | grep -o '[0-9]\+')"
day="$(printf "%02d\n" $raw_day)"

[ -d "$1" ] && exit

mkdir -p $1
cp -ar ./template/* ./$1/

echo "#!/bin/bash

echo \"============\"
echo \"== Day $day ==\"
echo \"============\"
echo \"\"

cd \"\$(dirname \"\$0\")\"

make > ./logs/make.log && cd bin
java Main
cd .." > ./$1/run
