#!/bin/bash

cd "$(dirname "$0")"

raw_day="$(echo "$1" | grep -o '[0-9]\+')"
[[ ${#raw_day} -gt 1 ]] && day="$raw_day" || day="$(printf "%02d\n" $raw_day)"

[ -d "day$day" ] && exit

mkdir -p "day$day"
cp -ar ./template/* "./day$day/"

echo "#!/bin/bash

echo \"============\"
echo \"== Day $day ==\"
echo \"============\"
echo \"\"

cd \"\$(dirname \"\$0\")\"

make > ./logs/make.log && cd bin
java Main
cd .." > ./$1/run
